config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :appointment_constraint
  get 'home/index'
  devise_for :users

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end
  

app/models/appointment_constraint.rb
class AppointmentConstraint < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #root to: "home#index"
end

app/controllers/appointment_constraint_controller.rb
class AppointmentConstraintController < ApplicationController
  protect_from_forgery except: :create 
  def new
    @daysOfWeek = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
    @appointmentconstraints = AppointmentConstraint.all
  end
  def create
    @daysOfWeek = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
    start_time = DateTime.new(params["appointment_constraint"]["input_start_time(1i)"].to_i, params["appointment_constraint"]["input_start_time(2i)"].to_i, params["appointment_constraint"]["input_start_time(3i)"].to_i, params["appointment_constraint"]["input_start_time(4i)"].to_i, params["appointment_constraint"]["input_start_time(5i)"].to_i)
    end_time = DateTime.new(params["appointment_constraint"]["input_end_time(1i)"].to_i, params["appointment_constraint"]["input_end_time(2i)"].to_i, params["appointment_constraint"]["input_end_time(3i)"].to_i, params["appointment_constraint"]["input_end_time(4i)"].to_i, params["appointment_constraint"]["input_end_time(5i)"].to_i)
    app = AppointmentConstraint.create(day: @daysOfWeek[(params["appointment_constraint"]["value"].to_i)], value: params["appointment_constraint"]["value"], start_time: start_time, end_time: end_time) 
    redirect_to new_appointment_constraint_path
  end
  def edit
    @appointment_constraint = AppointmentConstraint.find(params[:id])  
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    protect_from_forgery except: :create
    def new
    end
    def create
        date = params["date"].to_date
        start_time = DateTime.new(date.year, date.month, date.day, params["input_start_time(4i)"].to_i, params["input_start_time(5i)"].to_i)
        end_time = start_time + (params[:Appointment][:duration].to_i).minutes
        appointments_at_same_time = Appointment.where("end_time >?", start_time).and(Appointment.where.not("start_time >?", end_time))
        if (appointments_at_same_time.count) == 0
            app = Appointment.create(start_time: start_time, end_time: end_time)
            flash.notice = "Appointment Created #{params[:description]}"
        else
            flash.alert = "Appointment not created it coincided with another time."
        end
        redirect_to root_path
    end
    def index
        @appointments = Appointment.all
    end
    def update
        app = Appointment.find(params[:id])
        time = DateTime.new(params[:appointment]["start_time(1i)"].to_i, params[:appointment]["start_time(2i)"].to_i, params[:appointment]["start_time(3i)"].to_i, params[:appointment]["start_time(4i)"].to_i, params[:appointment]["start_time(5i)"].to_i)
        app.update(start_time: time)
        app.update(end_time: time + 30.minutes)
        redirect_to root_path
    end
    def edit
        @appointment = Appointment.find(params[:id])
    end
    def colission_check

    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointment_constraint_helper.rb
module AppointmentConstraintHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/appointment_constraint/edit.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-8 mt-3 mt-lg-5">
            <%= form_with model: @appointment_constraint, url: appointment_constraint_path(@appointment_constraint), html: {class: "form-control mb-3"}, data: {controller: "dropdown"}, method: :create do |form| %>
                <div class="d-flex justify-content-between">
                    <p class="my-1 dropdown-title">Edit Hours for <%= @appointment_constraint.day.humanize %></p>
                    <button type="button" class="btn btn-danger" data-action="click->dropdown#visibility" data-dropdown-target="hide_button"><i class="fa-solid fa-minus fa-2xs" data-dropdown-target="hide_icon"></i></button>
                </div>
                <div class="form-control mt-2" data-dropdown-target="hideable">
                    <div class="row">
                        <%= form.label "Start Time" %>
                        <%= form.time_select :input_start_time, {time_separator: "", date_separator: "", datetime_separator: "", ampm: true, minute_step: 15}, {class: "form-control my-2 mx-2 col"} %>
                        <%= form.label "End Time" %>
                        <%= form.time_select :input_end_time, {time_separator: "", date_separator: "", datetime_separator: "", ampm: true, minute_step: 15}, {class: "form-control my-2 mx-2 col"} %>
                    </div>
                    <div class="mx-md-5">
                        <%= form.submit "Save Edit", class: "btn btn-primary my-2 w-100" %>
                        <%= link_to "Delete Item", home_index_path, method: :get, class: "btn btn-danger mb-3 w-100" %>
                    </div>
                </div>
            <% end %>
            <div class="d-flex justify-content-between">
                <%= link_to "Back", new_appointment_constraint_path, method: :get, class: "btn btn-primary mb-3" %>
                <%= link_to "Home Page", home_index_path, method: :get, class: "btn btn-primary mb-3" %>
            </div>
        </div>
    </div>
</div>

app/views/appointment_constraint/index.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-8 mt-3 mt-lg-5">
            
        </div>
    </div>
</div>

app/views/appointment_constraint/new.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-8 mt-3 mt-lg-5">
            <div class = "form-control mb-3" data-controller="dropdown">
                <div class="d-flex justify-content-between">
                    <p class="my-1 dropdown-title">Current Hours</p>
                    <button class="btn btn-danger" data-action="click->dropdown#visibility" data-dropdown-target="hide_button"><i class="fa-solid fa-minus fa-2xs" data-dropdown-target="hide_icon"></i></button>
                </div>
                <% for i in 0..6 do %>
                    <%= render partial: 'appointment_constraint/partials/timetable', locals: { iteration: i } %>
                <% end %>
            </div>
            <%= form_with model: @appointmentconstraints, url: appointment_constraint_index_path(), html: {class: "form-control mb-3"}, data: {controller: "dropdown"}, method: :create do |form| %>
                <div class="d-flex justify-content-between">
                    <p class="my-1 dropdown-title">Create New Hours</p>
                    <button type="button" class="btn btn-danger" data-action="click->dropdown#visibility" data-dropdown-target="hide_button"><i class="fa-solid fa-minus fa-2xs" data-dropdown-target="hide_icon"></i></button>
                </div>
                <div class="form-control mt-2" data-dropdown-target="hideable">
                    <%= form.label "Select Day" %>
                    <select name="appointment_constraint[value]" class="form-control my-2">
                        <option value="0">Monday</option>
                        <option value="1">Tuesday</option>
                        <option value="2">Wednesday</option>
                        <option value="3">Thursday</option>
                        <option value="4">Friday</option>
                        <option value="5">Saturday</option>
                        <option value="6">Sunday</option>
                    </select>
                    <div class="row">
                        <%= form.label "Start Time" %>
                        <%= form.time_select :input_start_time, {time_separator: "", date_separator: "", datetime_separator: "", ampm: true, minute_step: 15}, {class: "form-control my-2 mx-2 col"} %>
                        <%= form.label "End Time" %>
                        <%= form.time_select :input_end_time, {time_separator: "", date_separator: "", datetime_separator: "", ampm: true, minute_step: 15}, {class: "form-control my-2 mx-2 col"} %>
                    </div>
                    <%= form.submit "Create New Hours", class: "btn btn-primary my-2 w-100" %>
                </div>
            <% end %>
            <div class="text-center">
                <%= link_to "Home Page", home_index_path, method: :get, class: "btn btn-danger mb-3" %>
            </div>
        </div>
    </div>
</div>

app/views/appointment_constraint/partials/_timetable.html.erb
<div class="mx-0 mt-2 form-control" data-dropdown-target="hideable">
  <div>
      <p class="mb-1"><%= @daysOfWeek[iteration].humanize %></p>
  </div>
  <div>
      <div class="row">
          <% @appointmentconstraints.where(value: iteration).each do |appConstraint| %>
              <div class="col-12 col-md-auto mb-2">
                  <%= button_to "#{appConstraint.start_time.strftime('%I:%M %p')}-#{appConstraint.end_time.strftime('%I:%M %p')}", edit_appointment_constraint_path(appConstraint.id), method: "get", class: "btn btn-outline-primary d-inline px-2 py-1 w-100", type: "button" %>
              </div>
          <% end %>
      </div>
  </div>
</div>

app/views/appointments/edit.html.erb
<h1> Edit Page <%=@appointment.id%> </h1>

<%= form_with model: @appointment, url: appointment_path(@appointment), method: :put do |form| %>
  <%= form.datetime_select :start_time, end_year: Date.current.year+1, start_year: Date.current.year, minute_step: 15 %>
  <%= form.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/appointments/index.html.erb
<h1> Appointments </h1>

<div class = "row container-fluid mx-0 px-0">
    <div class = "col-12 col-lg-9">
        <%= month_calendar(events: @appointments) do |date, app| %>
            <%= date.day %>
            <div>
              <% app.each do |app| %>
                <%= button_to "#{app.start_time.strftime('%H:%M %p')}-#{app.end_time.strftime('%H:%M %p')}", edit_appointment_path(app.id), method: :get, class: "btn btn-outline-primary mb-3" %>
              <% end %>
            </div>
        <% end %>
    </div>
    <div class = "col-12 col-lg-3">
        <h5> Upcoming Appointments Today</h5>
        <% @appointments.each do |app| %>
            <p> <%= app.id %> </p>
        <% end %>
    </div>
<div>
<%= link_to "Home Page", root_path, method: :get, class: "btn btn-primary" %>

app/views/appointments/new.html.erb
<div class="container-fluid">
    <h1>Create Appointment</h1>


    <div class="row justify-content-center">
        <div class="col-12 col-lg-5">
            <%= form_with model: @appointment, url: appointments_path(), html: {class: "form-control"}, data: {controller: "test"}, method: :create do |form| %>
                <div class="row mx-0">
                    <%= form.date_field :date, min: Date.today, max: Date.today + 1.month, class: "form-control my-2 col", data: {controller: "test", action: "change->test#output"} %>
                </div>
                <div class="row mx-0">
                    <%= form.time_select :input_start_time, {time_separator: "", date_separator: "", datetime_separator: "", ampm: true, minute_step: 15, start_hour: 10, end_hour: 18}, {class: "form-control my-2 col"} %>
                </div>
                <select name="Appointment[duration]" class="form-control my-2" >
                    <option value="15">15 Minutes</option>
                    <option value="30">30 Minutes</option>
                    <option value="45">45 Minutes</option>
                </select>
                <%= form.label "Enter appointment description", class: "mt-2 w-100" %>
                <%= form.text_area :description, rows: 5, class: "my-2 w-100" %>
                <%= form.submit "Create new Appointment", class: "btn btn-primary my-2 w-100" %>
            <% end %>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<p class = "h2">Home#index</h2>
<% if user_signed_in? %> <h1> <%= current_user %></h1> <% else %> <h1> NOT SINGED IN </h1> <% end %>

<%= link_to "Login", user_session_path, method: :get, class: "btn btn-primary" %>
<%= link_to "Sign up", new_user_registration_path, method: :get, class: "btn btn-primary" %>
<%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
<%= link_to "Create Appointment Page", new_appointment_path, method: :get, class: "btn btn-primary" %>
<%= link_to "Appointment Index", appointments_path, method: :get, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleCreator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>  <%# this loads Sprockets/Rails asset pipeline %>
    <%= javascript_importmap_tags %> <%#  this loads JS from importmaps %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view, class: "btn btn-primary" %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view, class: "btn btn-primary" %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>